[pytest]

# --- Output & Reporting --------------------------------------------
addopts =
    -ra
    --durations=10

# --- Test Discovery -------------------------------------------------
testpaths =
    test

# --- Warnings -------------------------------------------------------
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::pytest.PytestDeprecationWarning

# --- Logging --------------------------------------------------------
log_cli = true
log_cli_level = INFO

